# Desired parameters values
/mecanum_parameters_node:
  ros__parameters:
    robot_name: "Moaz Alnor Bot"
    robot_id: 82
    target_linear_velocity_x: 0.0
    target_linear_velocity_y: 0.0
    target_angular_velocity: 0.23